/**
 * Configuration management for GitHub Achievements Manager
 * Loads and validates settings from .env file
 */

import { config as dotenvConfig } from 'dotenv';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type { AppConfig, SetupAnswers } from '../types/index.js';
import { ConfigurationError, MissingConfigError } from './errors.js';

// Get the project root directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
export const PROJECT_ROOT = join(__dirname, '..', '..');

// Paths
export const ENV_PATH = join(PROJECT_ROOT, '.env');
export const ENV_EXAMPLE_PATH = join(PROJECT_ROOT, '.env.example');
export const DB_PATH = join(PROJECT_ROOT, 'achievements.db');
export const LOGS_DIR = join(PROJECT_ROOT, 'logs');
export const LANG_PATH = join(PROJECT_ROOT, '.language');

// Default configuration values
// Note: Each operation makes ~5 API calls (branch, commit, PR, merge, delete)
// GitHub's limit is 80 content-creating requests/minute
// So we limit to 15 operations/minute (75 API calls) to stay safe
const DEFAULTS = {
  coauthorName: 'n0',
  coauthorEmail: 'luke@u.software',
  branchPrefix: 'achievement',
  delayMs: 500,           // Delay between operations for stability
  batchSize: 5,
  verbose: false,
  testMode: false,
  logLevel: 'info' as const,
  concurrency: 2,         // Parallel operations (2 × 5 calls = 10 concurrent API calls max)
  maxRequestsPerMinute: 15, // Operations/minute (15 × 5 = 75 API calls, under 80 limit)
};

// Cached config instance
let cachedConfig: AppConfig | null = null;

/**
 * Check if .env file exists
 */
export function envFileExists(): boolean {
  return existsSync(ENV_PATH);
}

/**
 * Load configuration from .env file
 */
export function loadConfig(validate = true): AppConfig {
  // Return cached config if available
  if (cachedConfig) {
    return cachedConfig;
  }

  // Load .env file
  const result = dotenvConfig({ path: ENV_PATH });

  if (result.error && validate) {
    if (!envFileExists()) {
      throw new MissingConfigError('.env file');
    }
  }

  const env = process.env;

  // Build config object with defaults
  const config: AppConfig = {
    githubToken: env.GITHUB_TOKEN || '',
    githubUsername: env.GITHUB_USERNAME || '',
    targetRepo: env.TARGET_REPO || '',
    coauthorName: env.COAUTHOR_NAME || DEFAULTS.coauthorName,
    coauthorEmail: env.COAUTHOR_EMAIL || DEFAULTS.coauthorEmail,
    branchPrefix: env.BRANCH_PREFIX || DEFAULTS.branchPrefix,
    delayMs: parseInt(env.DELAY_MS || String(DEFAULTS.delayMs), 10),
    batchSize: parseInt(env.BATCH_SIZE || String(DEFAULTS.batchSize), 10),
    verbose: env.VERBOSE === 'true',
    testMode: env.TEST_MODE === 'true',
    logLevel: (env.LOG_LEVEL as AppConfig['logLevel']) || DEFAULTS.logLevel,
    // Concurrency settings
    concurrency: parseInt(env.CONCURRENCY || String(DEFAULTS.concurrency), 10),
    maxRequestsPerMinute: parseInt(env.MAX_REQUESTS_PER_MINUTE || String(DEFAULTS.maxRequestsPerMinute), 10),
    // Optional helper account for Galaxy Brain
    helperToken: env.HELPER_TOKEN || undefined,
    helperUsername: env.HELPER_USERNAME || undefined,
  };

  // Validate if required
  if (validate) {
    validateConfig(config);
  }

  cachedConfig = config;
  return config;
}

/**
 * Validate configuration
 */
export function validateConfig(config: AppConfig): void {
  // Check required fields
  if (!config.githubToken) {
    throw new MissingConfigError('GITHUB_TOKEN');
  }

  if (!config.githubToken.startsWith('ghp_') && !config.githubToken.startsWith('github_pat_')) {
    throw new ConfigurationError(
      'GITHUB_TOKEN',
      'Token should start with "ghp_" or "github_pat_". Generate a new token at https://github.com/settings/tokens'
    );
  }

  if (!config.targetRepo) {
    throw new MissingConfigError('TARGET_REPO');
  }

  // Validate target repo format
  if (!config.targetRepo.includes('/')) {
    throw new ConfigurationError(
      'TARGET_REPO',
      'Should be in format "owner/repo" (e.g., "myusername/my-repo")'
    );
  }

  // Validate numeric values
  if (isNaN(config.delayMs) || config.delayMs < 0) {
    throw new ConfigurationError('DELAY_MS', 'Must be a positive number');
  }

  if (isNaN(config.batchSize) || config.batchSize < 1) {
    throw new ConfigurationError('BATCH_SIZE', 'Must be a positive integer');
  }

  // Validate email format for coauthor
  if (config.coauthorEmail && !config.coauthorEmail.includes('@')) {
    throw new ConfigurationError('COAUTHOR_EMAIL', 'Must be a valid email address');
  }
}

/**
 * Create .env file from setup answers
 */
export function createEnvFile(answers: SetupAnswers, username: string): void {
  const content = `# GitHub Achievements Manager Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# ===========================================
# REQUIRED SETTINGS
# ===========================================

# Your GitHub Personal Access Token
GITHUB_TOKEN=${answers.githubToken}

# Your GitHub username
GITHUB_USERNAME=${username}

# Target repository for achievement creation
TARGET_REPO=${answers.targetRepo}

# ===========================================
# OPTIONAL SETTINGS
# ===========================================

# Coauthor for Pair Extraordinaire achievement
COAUTHOR_NAME=${answers.coauthorName || DEFAULTS.coauthorName}
COAUTHOR_EMAIL=${answers.coauthorEmail || DEFAULTS.coauthorEmail}

# Branch prefix for created branches
BRANCH_PREFIX=${answers.branchPrefix || DEFAULTS.branchPrefix}

# Delay between operations in milliseconds
DELAY_MS=${answers.delayMs || DEFAULTS.delayMs}

# ===========================================
# ADVANCED SETTINGS
# ===========================================

# Enable verbose logging
VERBOSE=false

# Enable test/dry-run mode
TEST_MODE=false

# Batch size for parallel operations
BATCH_SIZE=${DEFAULTS.batchSize}

# Log level: debug, info, warn, error
LOG_LEVEL=${DEFAULTS.logLevel}
${answers.helperToken ? `
# ===========================================
# GALAXY BRAIN HELPER ACCOUNT
# ===========================================
# Second GitHub account for Galaxy Brain achievement
# This account creates questions, your main account answers them
HELPER_TOKEN=${answers.helperToken}
` : ''}`;

  writeFileSync(ENV_PATH, content, 'utf-8');

  // Clear cached config
  cachedConfig = null;
}

/**
 * Update a single config value in .env file
 */
export function updateEnvValue(key: string, value: string): void {
  if (!envFileExists()) {
    throw new MissingConfigError('.env file');
  }

  let content = readFileSync(ENV_PATH, 'utf-8');
  const regex = new RegExp(`^${key}=.*$`, 'm');

  if (regex.test(content)) {
    content = content.replace(regex, `${key}=${value}`);
  } else {
    content += `\n${key}=${value}\n`;
  }

  writeFileSync(ENV_PATH, content, 'utf-8');

  // Clear cached config
  cachedConfig = null;
}

/**
 * Parse repository string into owner and repo
 */
export function parseRepo(repoString: string): { owner: string; repo: string } {
  const parts = repoString.split('/');

  if (parts.length !== 2) {
    throw new ConfigurationError(
      'TARGET_REPO',
      `Invalid format "${repoString}". Expected "owner/repo".`
    );
  }

  return {
    owner: parts[0].trim(),
    repo: parts[1].trim(),
  };
}

/**
 * Get the full coauthor trailer for commit messages
 */
export function getCoauthorTrailer(config: AppConfig): string {
  return `Co-authored-by: ${config.coauthorName} <${config.coauthorEmail}>`;
}

/**
 * Clear cached configuration (useful for testing or re-loading)
 */
export function clearConfigCache(): void {
  cachedConfig = null;
}

/**
 * Get default configuration (for display in setup wizard)
 */
export function getDefaults(): typeof DEFAULTS {
  return { ...DEFAULTS };
}

/**
 * Check if running in test/dry-run mode
 */
export function isDryRun(): boolean {
  try {
    const config = loadConfig(false);
    return config.testMode;
  } catch {
    return false;
  }
}

/**
 * Check if verbose mode is enabled
 */
export function isVerbose(): boolean {
  try {
    const config = loadConfig(false);
    return config.verbose;
  } catch {
    return false;
  }
}

/**
 * Check if language has been set
 */
export function languageFileExists(): boolean {
  return existsSync(LANG_PATH);
}

/**
 * Get saved language
 */
export function getSavedLanguage(): string | null {
  if (!languageFileExists()) {
    return null;
  }
  try {
    return readFileSync(LANG_PATH, 'utf-8').trim();
  } catch {
    return null;
  }
}

/**
 * Save language preference
 */
export function saveLanguage(lang: string): void {
  writeFileSync(LANG_PATH, lang, 'utf-8');
}
